changelog:
  categories:
    - title: 기능(LP)
      labels:
        - LP:기능
    - title: 기능(TS)
      labels:
        - TS:기능
    - title: 버그 픽스(LP)
      labels:
        - LP:버그 픽스
    - title: 버그 픽스(TS)
      labels:
        - TS:버그 픽스
    - title: 기타
      labels:
        - '*'
