name: get_package_version
description: 'use this action to get a latest tag of package'
inputs:
  package:
    required: true
outputs:
  version:
    value: ${{ steps.get-tag.outputs.result }}

runs:
  using: 'composite'
  steps:
    - id: get-tag
      shell: bash
      run: |
        git fetch --all --tags

        last_commit=`git log -n 1 --pretty=format:"%H"`

        echo $last_commit

        echo `git tag -l --sort -v:refname "${{ inputs.package }}/*" | head -n 1`

        echo `git tag -l --sort -v:refname "${{ inputs.package }}/*" --merged fc561fd8201b3a4bef221fd0d08825f98d04c569 | head -n 1`

        echo "$(git tag -l --sort -v:refname "${{ inputs.package }}/*" --merged $last_commit | head -n 1)""

        echo "result=$(echo `git tag -l --sort -v:refname "${{ inputs.package }}/*" --merged $last_commit | head -n 1` | cut -d/ -f2)" >> $GITHUB_OUTPUT
