name: get_package_version
description: 'use this action to get a latest tag of package'
inputs:
  package:
    required: true
outputs:
  version:
    value: ${{ steps.get-tag.outputs.result }}

runs:
  using: 'composite'
  steps:
    - id: get-commit-id
      shell: bash
      run: |
        last_commit=`git log -n 1 --pretty=format:"%H"`

        echo $last_commit

        echo "result=$last_commit" >> $GITHUB_OUTPUT

    - id: get-tag
      shell: bash
      run: |
        git fetch --all --tags

        echo ${{ steps.get-commit-id.outputs.result }}

        tag=$(echo `git tag -l --sort -v:refname "${{ inputs.package }}/*" --merged ${{ steps.get-commit-id.outputs.result }} | head -n 1` | cut -d/ -f2)

        echo latest tag: $tag

        echo "result=$tag" >> $GITHUB_OUTPUT
