name: get_package_version
description: 'use this action to get a latest tag of package'
inputs:
  package:
    required: true
outputs:
  version:
    value: ${{ steps.get-tag.outputs.result }}

runs:
  using: 'composite'
  steps:
    - id: get-tag
      shell: bash
      run: |
        echo $(git describe --abbrev=0 --tags --match="${{ inputs.package }}/*" $(git log -n 1 --pretty=format:"%H"))

        # git fetch ${{ github.ref_name }}

        # echo ${{ steps.get-commit-id.outputs.result }}

        # echo $(git rev-parse --abbrev-ref HEAD)

        # echo $(git tag -l --sort -v:refname "${{ inputs.package }}/*" --merged $(git rev-parse --abbrev-ref HEAD))

        # tag=$(echo `git tag -l --sort -v:refname "${{ inputs.package }}/*" --merged $(git rev-parse --abbrev-ref HEAD) | head -n 1` | cut -d/ -f2)

        tag=$(echo `git describe --abbrev=0 --tags --match="${{ inputs.package }}/*" $(git log -n 1 --pretty=format:"%H") | head -n 1` | cut -d/ -f2)

        echo latest tag: $tag

        echo "result=$tag" >> $GITHUB_OUTPUT
