name: get_package_version
description: 'use this action to get a latest tag of package'
inputs:
  package:
    required: true
outputs:
  version:
    value: ${{ steps.get-tag.outputs.result }}

runs:
  using: 'composite'
  steps:
    - id: get-tag
      shell: bash
      run: |
        git fetch --all --tags

        latest_commit=`git log -n 1 --pretty=format:"%H"`

        echo "result=$(echo `git tag -l --sort -v:refname "${{ inputs.package }}/*" --merged $latest_commit | head -n 1` | cut -d/ -f2)" >> $GITHUB_OUTPUT
