name: get_package_version
description: 'use this action to get a latest tag of package'
inputs:
  package:
    required: true
outputs:
  version:
    value: ${{ steps.get-tag.outputs.result }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - id: get-tag
      shell: bash
      run: |
        git fetch --all --tags

        tag=$(echo `git tag -l --sort -v:refname "${{ inputs.package }}/*" | head -n 1` | cut -d/ -f2)

        echo latest tag: $tag
        echo "result=$tag" >> $GITHUB_OUTPUT
