# !1 local qa -> remote qa -> minor up (on push)
# !2 remote fix -> remote qa -> patch up (on PR) -> push

name: versioning

on:
  push:
    branches:
      - master

jobs:
  minor:
    if: contains(github.event.head_commit.message, 'Merge pull request') == false
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo 'pushed !, lets up minor !'
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.event.head_commit.message }}
