name: notify

on: workflow_call

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: workflow_logs

      - run: cat log_${{ github.run_id }}.txt > error_log

      - name: Set Slack Message
        run: |
          echo 'SLACK_MESSAGE<<EOF' >> $GITHUB_ENV
          echo -e '\n' >> $GITHUB_ENV
          head -n 10 error_log >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Send a message to Slack in case of failure
        run: echo "send !"
