name: pr-base-trigger

on:
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  changes:
    if: github.event.pull_request.state != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            lp:
              - 'packages/lp/**'
            ts:
              - 'packages/ts/**'

  lp_cd:
    needs: [changes]
    if: needs.changes.result == 'success' && contains(github.event.pull_request.labels.*.name, 'action:cd')
    runs-on: ubuntu-latest
    steps:
      - run: echo "cd lp"

  ts_cd:
    needs: [changes]
    if: needs.changes.result == 'success' && contains(github.event.pull_request.labels.*.name, 'action:cd')
    runs-on: ubuntu-latest
    steps:
      - run: echo "cd ts"
