const b = {
  after: '5c68ff52452716ee3aa6656cd2475b86f4b23292',
  base_ref: null,
  before: '15927f9b89a8eb2aebd19833686fc61ea9dfa122',
  commits: [
    {
      author: {
        email: 'rheech22@gmail.com',
        name: 'Aiden',
        username: 'rheech22',
      },
      committer: {
        email: 'rheech22@gmail.com',
        name: 'Aiden',
        username: 'rheech22',
      },
      distinct: false,
      id: 'f50311ac8df3ce4c79672e1df04d6e672bdf7194',
      message: '1232:',
      timestamp: '2023-12-07T02:05:51+09:00',
      tree_id: '7b40be3c708262b423aee3ddae0c797835b98b04',
      url: 'https://github.com/chyukTW/gh-action/commit/f50311ac8df3ce4c79672e1df04d6e672bdf7194',
    },
    {
      author: {
        email: '103919739+chyukTW@users.noreply.github.com',
        name: '이창혁',
        username: 'chyukTW',
      },
      committer: {
        email: 'noreply@github.com',
        name: 'GitHub',
        username: 'web-flow',
      },
      distinct: true,
      id: '5c68ff52452716ee3aa6656cd2475b86f4b23292',
      message: 'Merge pull request #112 from chyukTW/fix-123213\n\n1232:',
      timestamp: '2023-12-07T02:06:17+09:00',
      tree_id: '7b40be3c708262b423aee3ddae0c797835b98b04',
      url: 'https://github.com/chyukTW/gh-action/commit/5c68ff52452716ee3aa6656cd2475b86f4b23292',
    },
  ],
  compare:
    'https://github.com/chyukTW/gh-action/compare/15927f9b89a8...5c68ff524527',
  created: false,
  deleted: false,
  forced: false,
  head_commit: {
    author: {
      email: '103919739+chyukTW@users.noreply.github.com',
      name: '이창혁',
      username: 'chyukTW',
    },
    committer: {
      email: 'noreply@github.com',
      name: 'GitHub',
      username: 'web-flow',
    },
    distinct: true,
    id: '5c68ff52452716ee3aa6656cd2475b86f4b23292',
    message: 'Merge pull request #112 from chyukTW/fix-123213\n\n1232:',
    timestamp: '2023-12-07T02:06:17+09:00',
    tree_id: '7b40be3c708262b423aee3ddae0c797835b98b04',
    url: 'https://github.com/chyukTW/gh-action/commit/5c68ff52452716ee3aa6656cd2475b86f4b23292',
  },
  pusher: {
    email: '103919739+chyukTW@users.noreply.github.com',
    name: 'chyukTW',
  },
  ref: 'refs/heads/lp-qa',
  repository: {
    allow_forking: true,
    archive_url:
      'https://api.github.com/repos/chyukTW/gh-action/{archive_format}{/ref}',
    archived: false,
    assignees_url:
      'https://api.github.com/repos/chyukTW/gh-action/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/chyukTW/gh-action/git/blobs{/sha}',
    branches_url:
      'https://api.github.com/repos/chyukTW/gh-action/branches{/branch}',
    clone_url: 'https://github.com/chyukTW/gh-action.git',
    collaborators_url:
      'https://api.github.com/repos/chyukTW/gh-action/collaborators{/collaborator}',
    comments_url:
      'https://api.github.com/repos/chyukTW/gh-action/comments{/number}',
    commits_url: 'https://api.github.com/repos/chyukTW/gh-action/commits{/sha}',
    compare_url:
      'https://api.github.com/repos/chyukTW/gh-action/compare/{base}...{head}',
    contents_url:
      'https://api.github.com/repos/chyukTW/gh-action/contents/{+path}',
    contributors_url:
      'https://api.github.com/repos/chyukTW/gh-action/contributors',
    created_at: 1680513362,
    default_branch: 'master',
    deployments_url:
      'https://api.github.com/repos/chyukTW/gh-action/deployments',
    description: null,
    disabled: false,
    downloads_url: 'https://api.github.com/repos/chyukTW/gh-action/downloads',
    events_url: 'https://api.github.com/repos/chyukTW/gh-action/events',
    fork: false,
    forks: 0,
    forks_count: 0,
    forks_url: 'https://api.github.com/repos/chyukTW/gh-action/forks',
    full_name: 'chyukTW/gh-action',
    git_commits_url:
      'https://api.github.com/repos/chyukTW/gh-action/git/commits{/sha}',
    git_refs_url:
      'https://api.github.com/repos/chyukTW/gh-action/git/refs{/sha}',
    git_tags_url:
      'https://api.github.com/repos/chyukTW/gh-action/git/tags{/sha}',
    git_url: 'git://github.com/chyukTW/gh-action.git',
    has_discussions: false,
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: 'https://api.github.com/repos/chyukTW/gh-action/hooks',
    html_url: 'https://github.com/chyukTW/gh-action',
    id: 622890218,
    is_template: false,
    issue_comment_url:
      'https://api.github.com/repos/chyukTW/gh-action/issues/comments{/number}',
    issue_events_url:
      'https://api.github.com/repos/chyukTW/gh-action/issues/events{/number}',
    issues_url:
      'https://api.github.com/repos/chyukTW/gh-action/issues{/number}',
    keys_url: 'https://api.github.com/repos/chyukTW/gh-action/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/chyukTW/gh-action/labels{/name}',
    language: 'CSS',
    languages_url: 'https://api.github.com/repos/chyukTW/gh-action/languages',
    license: null,
    master_branch: 'master',
    merges_url: 'https://api.github.com/repos/chyukTW/gh-action/merges',
    milestones_url:
      'https://api.github.com/repos/chyukTW/gh-action/milestones{/number}',
    mirror_url: null,
    name: 'gh-action',
    node_id: 'R_kgDOJSCM6g',
    notifications_url:
      'https://api.github.com/repos/chyukTW/gh-action/notifications{?since,all,participating}',
    open_issues: 0,
    open_issues_count: 0,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/103919739?v=4',
      email: '103919739+chyukTW@users.noreply.github.com',
      events_url: 'https://api.github.com/users/chyukTW/events{/privacy}',
      followers_url: 'https://api.github.com/users/chyukTW/followers',
      following_url:
        'https://api.github.com/users/chyukTW/following{/other_user}',
      gists_url: 'https://api.github.com/users/chyukTW/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/chyukTW',
      id: 103919739,
      login: 'chyukTW',
      name: 'chyukTW',
      node_id: 'U_kgDOBjGwew',
      organizations_url: 'https://api.github.com/users/chyukTW/orgs',
      received_events_url:
        'https://api.github.com/users/chyukTW/received_events',
      repos_url: 'https://api.github.com/users/chyukTW/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/chyukTW/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/chyukTW/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/chyukTW',
    },
    private: false,
    pulls_url: 'https://api.github.com/repos/chyukTW/gh-action/pulls{/number}',
    pushed_at: 1701882377,
    releases_url:
      'https://api.github.com/repos/chyukTW/gh-action/releases{/id}',
    size: 263,
    ssh_url: 'git@github.com:chyukTW/gh-action.git',
    stargazers: 0,
    stargazers_count: 0,
    stargazers_url: 'https://api.github.com/repos/chyukTW/gh-action/stargazers',
    statuses_url:
      'https://api.github.com/repos/chyukTW/gh-action/statuses/{sha}',
    subscribers_url:
      'https://api.github.com/repos/chyukTW/gh-action/subscribers',
    subscription_url:
      'https://api.github.com/repos/chyukTW/gh-action/subscription',
    svn_url: 'https://github.com/chyukTW/gh-action',
    tags_url: 'https://api.github.com/repos/chyukTW/gh-action/tags',
    teams_url: 'https://api.github.com/repos/chyukTW/gh-action/teams',
    topics: [],
    trees_url: 'https://api.github.com/repos/chyukTW/gh-action/git/trees{/sha}',
    updated_at: '2023-05-15T09:33:37Z',
    url: 'https://github.com/chyukTW/gh-action',
    visibility: 'public',
    watchers: 0,
    watchers_count: 0,
    web_commit_signoff_required: false,
  },
  sender: {
    avatar_url: 'https://avatars.githubusercontent.com/u/103919739?v=4',
    events_url: 'https://api.github.com/users/chyukTW/events{/privacy}',
    followers_url: 'https://api.github.com/users/chyukTW/followers',
    following_url:
      'https://api.github.com/users/chyukTW/following{/other_user}',
    gists_url: 'https://api.github.com/users/chyukTW/gists{/gist_id}',
    gravatar_id: '',
    html_url: 'https://github.com/chyukTW',
    id: 103919739,
    login: 'chyukTW',
    node_id: 'U_kgDOBjGwew',
    organizations_url: 'https://api.github.com/users/chyukTW/orgs',
    received_events_url: 'https://api.github.com/users/chyukTW/received_events',
    repos_url: 'https://api.github.com/users/chyukTW/repos',
    site_admin: false,
    starred_url: 'https://api.github.com/users/chyukTW/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/chyukTW/subscriptions',
    type: 'User',
    url: 'https://api.github.com/users/chyukTW',
  },
};
