name: called

on:
  workflow_call:
    inputs:
      runId:
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: gh run download ${{ inputs.runId }} -n workflow_log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
