name: caller

on: push

jobs:
  success:
    uses: ./.github/workflows/success-upload.yml

  failure:
    needs: success
    if: ${{ always() && needs.success.result == 'success' }}
    uses: ./.github/workflows/failure-upload.yml

  summary:
    needs: [success, failure]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/summary.yml

  notify:
    needs: [success, failure]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/notify.yml

  # call_cd:
  #   needs: failed
  #   if: needs.failed.result == 'success'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "call cd"
