name: called

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}

      - name: Display structure of downloaded files
        run: ls -al

      - name: cat
        run: cat ${{ inputs.path }}

    # steps:
    #   - uses: actions/checkout@v3

    #   - run: gh run download ${{ inputs.runId }} -n workflow_log
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
