name: caller

on: push

jobs:
  success:
    uses: ./.github/workflows/success-upload.yml

  failure:
    needs: success
    if: needs.success.result == 'success'
    uses: ./.github/workflows/failure-upload.yml

  call_cd:
    needs: success
    if: needs.success.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo "call cd"

  summary:
    needs: [success, failure, call_cd]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/summary.yml

  notify:
    needs: [success, failure, call_cd]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/notify.yml
