name: caller

on: push

jobs:
  failed:
    runs-on: ubuntu-latest
    steps:
      - name: start
        id: start
        run: yarn start &> log_${{ github.run_id }}.txt

      - name: upload
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: workflow_logs
          path: log_${{ github.run_id }}.txt
          if-no-files-found: error
          retention-days: 1

  summary:
    needs: failed
    if: ${{ always() && needs.failed.result != 'success' }}
    uses: ./.github/workflows/summary.yml

  notify:
    needs: failed
    if: ${{ always() && needs.failed.result != 'success' }}
    uses: ./.github/workflows/notify.yml

  call_cd:
    needs: failed
    if: needs.failed.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo "call cd"
