name: caller

on: push

jobs:
  failed:
    runs-on: ubuntu-latest
    steps:
      - run: yarn start

  upload:
    needs: [failed]
    if: ${{ always() && !contains(join(needs.*.result, ','), 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "this is log" > log_${{ github.run_id }}.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: workflow_logs
          path: log_${{ github.run_id }}.txt
          if-no-files-found: error
          retention-days: 1

  summary:
    needs: upload
    if: ${{ always() && needs.upload.result == 'success' }}
    uses: ./.github/workflows/lp/summary.yml
    with:
      name: workflow_logs
      path: log_${{ github.run_id }}.txt

  notify:
    needs: upload
    if: ${{ always() && needs.upload.result == 'success' }}
    uses: ./.github/workflows/ts/notify.yml
    with:
      name: workflow_logs
      path: log_${{ github.run_id }}.txt
