name: caller

on: push

jobs:
  failed:
    runs-on: ubuntu-latest
    steps:
      - run: yarn start

  upload:
    needs: failed
    if: needs.failed.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "this is log" > log_${{ github.run_id }}.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: workflow_logs
          path: log_${{ github.run_id }}.txt
          if-no-files-found: error
          retention-days: 1

  summary:
    needs: upload
    if: needs.upload.result == 'success'
    uses: ./.github/workflows/summary.yml
    with:
      name: workflow_logs
      path: log_${{ github.run_id }}.txt

  notify:
    needs: upload
    if: needs.upload.result == 'success'
    uses: ./.github/workflows/notify.yml
    with:
      name: workflow_logs
      path: log_${{ github.run_id }}.txt
