name: cd

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      branch: ${{ steps.get-branch.outputs.public_branch }}
      version: ${{ steps.get-latest-version.outputs.version }}
      deployment: https://${{ steps.get-bucket-name.outputs.bucketName }}
    steps:
      - id: get-branch
        run: echo "public_branch=DEV" >> "$GITHUB_OUTPUT"
      - id: get-latest-version
        run: echo "version=v0.1.21" >> "$GITHUB_OUTPUT"
      - id: get-bucket-name
        run: echo "bucketName=dev-lp-mp.taras.twinny.ai" >> "$GITHUB_OUTPUT"
      # - id: failure
      #   run: exit 1

  notification:
    if: ${{ needs.deploy.outputs.branch }} != 'DEV'
    name: notification
    needs: deploy
    uses: ./.github/workflows/notify.yml
    with:
      package: LP
      branch: ${{ needs.deploy.outputs.branch }}
      version: ${{ needs.deploy.outputs.version }}
      deployment: ${{ needs.deploy.outputs.deployment }}
      patch_note: https://www.notion.so/twinny/704f3b548f9940298f5f59ef6eab460e?v=65dbd47e960c4936aec2ae71ab9c3ff2&pvs=4
    secrets: inherit
