name: push-by-path

on:
  push:
    branches:
      - 'master'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      lp: ${{ steps.filter.outputs.lp }}
      ts: ${{ steps.filter.outputs.ts }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            lp:
              - 'packages/lp/**'
            ts:
              - 'packages/ts/**'

  lp:
    needs: changes
    if: ${{ needs.changes.outputs.lp == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: CI(LP)
        run: echo "ci lp"

  ts:
    needs: changes
    if: ${{ needs.changes.outputs.ts == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: CI(TS)
        run: echo "ci ts"
