name: push-by-path

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            lp:
              - 'packages/lp/**'
            ts:
              - 'packages/ts/**'

      - name: CI(LP)
        if: steps.filter.outputs.lp == 'true'
        run: echo "ci lp"

      # run only if 'frontend' files were changed
      - name: CI(TS)
        if: steps.filter.outputs.ts == 'true'
        run: echo "ci ts"
