name: TEST_1

on:
  push:
    branches:
      - master
      - 'feat/**'

jobs:
  integration:
    if: github.event_name == 'push'
    name: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: ls
        run: ls -al

      - name: Install dependencies
        id: install_dependencies
        run: yarn install 2> >(tee error.log >&2) | tee /dev/null || return 1

      - name: Run test
        id: test
        run: yarn test 2> >(tee error.log >&2) | tee /dev/null || return 1

      - name: Print
        if: always()
        run: cat error.log
