name: TEST_1

on:
  push:
    branches:
      - master
      - 'feat/**'

jobs:
  integration:
    if: github.event_name == 'push'
    name: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        id: install_dependencies
        run: |
          yarn install 2>&1 | tee error.log
          if [ "${PIPESTATUS[0]}" -ne 0 ]; then
            echo "yarn install failed."
            exit 1
          fi

      - name: Run test
        id: test
        run: |
          yarn test 2>&1 | tee error.log
          if [ "${PIPESTATUS[0]}" -ne 0 ]; then
            echo "yarn test failed."
            exit 1
          fi

      - name: Print
        if: always()
        run: cat error.log
