name: TEST_1

on:
  push:
    branches:
      - master
      - 'feat/**'

jobs:
  integration:
    if: github.event_name == 'push'
    name: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        id: install_dependencies
        run: yarn install 2> >(tee error.log >&2) | tee /dev/null ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." >&2; exit 1; }

      - name: Run build
        id: build
        run: yarn build &> >(tee error.log >&2) | tee /dev/null ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn build failed." >&2; exit 1; }

      - name: Run test
        id: test
        run: yarn test 2> >(tee temp >&2) | tee /dev/null ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn test failed." >&2; exit 1; }

      - name: Get failed test title
        if: failure() && steps.test.outcome != 'success'
        run: cat temp | grep error > error.log

      - name: Print
        if: always()
        run: cat error.log
