name: TEST_1

on:
  push:
    branches:
      - master
      - 'feat/**'

jobs:
  integration:
    if: github.event_name == 'push'
    name: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        id: install_dependencies
        run: yarn install 2> >(tee error_log) ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." ; exit 1; }

      - name: Run build
        id: build
        run: yarn build &> >(tee error_log) ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn build failed." ; exit 1; }

      - name: Run test
        id: test
        run: yarn test 2> >(tee test_log) ; test ${PIPESTATUS[0]} -eq 0 || { echo "yarn test failed." ; exit 1; }

      - name: Get failed test title
        if: failure() && steps.test.outcome == 'failure'
        run: cat test_log | grep error > error_log

      - name: Failure Summary
        if: ${{ failure() }}
        run: |
          echo 'SLACK_MESSAGE<<EOF' >> $GITHUB_ENV
          head -n 10 error_log.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo '<details><summary>:boom: View error log</summary>' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo `cat error_log` >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '</details>' >> $GITHUB_STEP_SUMMARY
          if [ ${{steps.test.outcome}} == 'failure' ]; then
            echo '<details><summary>:fire: View test result</summary>' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            echo `cat test_log` >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo '</details>' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Set Slack Message
        if: failure()
        run: |
          echo 'SLACK_MESSAGE<<EOF' >> $GITHUB_ENV
          head -n 10 error_log >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Send status to Slack channel in case of failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_CHANNEL: development
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://user-images.githubusercontent.com/103919739/177964568-30ec9c4d-9528-4c88-8191-364ee4033d3c.png
          SLACK_TITLE: 'Failed with this error:'
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}
          SLACK_USERNAME: AC BOT
