name: pr context

on:
  pull_request:
    types:
      - closed

jobs:
  echo:
    if: contains(github.event.pull_request.labels.*.name, 'action:cd')
    name: echo context information
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: get branch
        id: get-branch
        run: |
          _branch=$(echo ${{ github.head_ref }} | cut -d'/' -f2 | cut -f2 -d '#')
          echo "branch=${_branch,,}" >> $GITHUB_OUTPUT

      - name: get bucket object
        id: get-bucket-object
        run: |
          _bucketName="feat-lp-mp.taras.twinny.ai/${{ steps.get-branch.outputs.branch }}"
          echo "bucket_name=${_bucketName,,}" >> $GITHUB_OUTPUT

      - name: echo result
        run: echo ${{ steps.get-bucket-object.outputs.bucket_name }}
