name: pr-closed

on:
  pull_request:
    types:
      - closed

jobs:
  echo:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'action:cd') }}
    name: echo context information
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: get label
        run: |
          echo ${{ contains(github.event.pull_request.labels.*.name, 'action:cd') }}
          echo ${{ toJson(github.event.pull_request.labels) }}
          echo ${{ github.event.pull_request.labels.*.name }}
          echo ${{ github.event.pull_request.labels.name }}

      - name: get branch
        run: |
          echo ${{ github.event.ref }}
          echo ${{ github.head_ref }}

      - name: get bucket name
        run: echo "do later"
