name: if-merged

on:
  pull_request:
    types:
      - closed

jobs:
  changes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      lp: ${{ steps.filter.outputs.lp }}
      ts: ${{ steps.filter.outputs.ts }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            lp:
              - 'packages/lp/**'
            ts:
              - 'packages/ts/**'

  lp_versioning:
    needs: changes
    if: needs.changes.outputs.lp == 'true'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.update-minor.outputs.version }}
      assignee: ${{ steps.update-minor.outputs.assignee }}
    steps:
      - uses: actions/checkout@v3

      - id: get-version
        uses: ./.github/actions/get_package_version
        with:
          package: lp

      - id: update-minor
        if: github.ref_name == 'master'
        uses: ./.github/actions/auto_versioning
        with:
          package: lp
          segment: minor
          previous: ${{ steps.get-version.outputs.version }}
          description: ${{ github.event.pull_request.title }}

      - id: update-patch
        if: github.ref_name == 'lp-qa'
        uses: ./.github/actions/auto_versioning
        with:
          package: lp
          segment: patch
          previous: ${{ steps.get-version.outputs.version }}
          description: ${{ github.event.pull_request.title }}

  ts_versioning:
    needs: changes
    if: needs.changes.outputs.ts == 'true'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.update-minor.outputs.version }}
      assignee: ${{ steps.update-minor.outputs.assignee }}
    steps:
      - uses: actions/checkout@v3

      - id: get-version
        uses: ./.github/actions/get_package_version
        with:
          package: ts

      - id: update-minor
        if: github.ref_name == 'master'
        uses: ./.github/actions/auto_versioning
        with:
          package: ts
          segment: minor
          previous: ${{ steps.get-version.outputs.version }}
          description: ${{ github.event.pull_request.title }}

      - id: update-patch
        if: github.ref_name == 'ts-qa'
        uses: ./.github/actions/auto_versioning
        with:
          package: ts
          segment: patch
          previous: ${{ steps.get-version.outputs.version }}
          description: ${{ github.event.pull_request.title }}

  notion_versioning:
    needs: [lp_versioning, ts_versioning]
    if: always() && (needs.lp_versioning.result == 'success' || needs.ts_versioning.result == 'success')
    runs-on: unbuntu-latest
    steps:
      - run: |
          echo "${{ github.event.pull_request.title }}"
          echo "${{ needs.lp_versioning.outputs.assignee }}"
          echo "${{ needs.lp_versioning.outputs.version }}"
          echo "${{ needs.ts_versioning.outputs.assignee }}"
          echo "${{ needs.ts_versioning.outputs.version }}"
