# !1 local qa -> remote qa -> minor up (on push)
# !2 remote fix -> remote qa -> patch up (on PR) -> push

name: versioning

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
    types:
      - closed

jobs:
  minor:
    if: github.event_name == 'push' && github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo 'pushed !, lets up minor !'
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
