name: deployment_notify

on: workflow_call

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set a Message
        run: |
          slack_message="
          *  환경:* DEV
          *  버전:* v0.150.0
          *  배포:* <https://dev-lp-mp.taras.twinny.ai| 링크>
          *  패치노트:* <https://www.notion.so/twinny/704f3b548f9940298f5f59ef6eab460e?v=65dbd47e960c4936aec2ae71ab9c3ff2&pvs=4| 링크>"

          echo 'SLACK_MESSAGE<<EOF' >> $GITHUB_ENV
          echo -e '\n' >> $GITHUB_ENV
          echo "$slack_message" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Send to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: noti
          SLACK_ICON: https://github.com/twinnylab/taras-web/assets/103919739/64a75295-53ff-4fe8-a5df-e72465fdaa29
          SLACK_USERNAME: LP-MP-BOT
          SLACK_TITLE: '[LP-MP 배포 완료]'
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}
          MSG_MINIMAL: true
