name: deployment_notify

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      branch:
        required: true
        type: string
      version:
        required: true
        type: string
      deployment:
        required: true
        type: string
      patch_note:
        required: true
        type: string

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set a Message
        run: |
          slack_message="
          *  환경:* ${{ inputs.branch }}
          *  버전:* ${{ inputs.version }}
          *  배포:* <${{ inputs.deployment }}| 클릭>
          *  패치노트:* <${{ inputs.patch_note }}| 클릭>"

          echo 'SLACK_MESSAGE<<EOF' >> $GITHUB_ENV
          echo "$slack_message" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Send to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: noti
          SLACK_ICON: https://github.com/chyukTW/onboarding/assets/103919739/f5595f6c-0380-485a-9acf-ea47409bbe12
          SLACK_USERNAME: ${{ inputs.package }}-MP-BOT
          SLACK_MSG_AUTHOR: false
          SLACK_TITLE: '[${{ inputs.package }}-MP 배포 완료]'
          SLACK_COLOR: '#5E3FDD'
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
