# !1 local qa -> remote qa -> minor up (on push)
# !2 remote fix -> remote qa -> patch up (on PR) -> push

name: minor

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  patch:
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'test')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'pushed !, lets up patch !'
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
