on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - if: contains(join(github.event.pull_request.labels.*.name, '|'), '기능')
        name: Update Minor
        run: |
          echo "Update Minor"
