on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get Label Name
        id: get_label_name
        env:
          LABEL_NAME: ${{ github.event.pull_request.labels[0].name }}
        run: |
          echo "$LABEL_NAME"
