name: PR merged - label

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get Label String
        id: get_labels
        run: |
          echo "string=${{ join(github.event.pull_request.labels.*.name, '|') }}" >> $GITHUB_OUTPUT

      - name: Get Version Type
        id: get_version_type
        run: |
          if [[ ${{ contains( steps.get_labels.outputs.string , 'BREAKING CHANGE') }} ]]
          then
            _type="major"
          elif [[ ${{ contains( steps.get_labels.outputs.string , '버그') }} ]]
          then 
            _type="patch"
          else
            _type="minor"
          fi
          echo "type=${_type,,}" >> $GITHUB_OUTPUT

      # ! 만약 TS랑 core랑 같이 바뀌면 어떻게 하나?

      - name: Get Package Name
        id: get_package_name
        run: |
          if [[ ${{ contains( steps.get_labels.outputs.string , 'TS') }} ]]
          then
            _packageName="TS"
          elif [[ ${{ contains( steps.get_labels.outputs.string , 'LP') }} ]]
          then 
            _packageName="LP"
          elif [[ ${{ contains( steps.get_labels.outputs.string , 'core') }} ]]
          then 
            _packageName="core"
          else
            _packageName="root"
          fi
          echo "packageName=${_packageName,,}" >> $GITHUB_OUTPUT

      - if: steps.get_package_name.outputs.packageName != 'root'
        uses: ./.github/workflows/tagging.yml
        with:
          packageName: ${{ steps.get_package_name.outputs.packageName }}
          type: ${{ steps.get_version_type.outputs.type }}
