# !1 local qa -> remote qa -> minor up (on push)

# !2 remote fix -> remote qa -> patch up (on PR) -> push

name: versioning

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - id: merged
        if: github.event.pull_request.merged == true
        run: |
          echo 'merged !'
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}

      - id: pushed
        run: |
          echo 'pushed !'
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0

      # - id: get-latest-version
      #   uses: ./.github/actions/get_latest_version
      #   with:
      #     package: lp

      # - id: minor
      #   uses: ./.github/actions/auto_versioning
      #   with:
      #     package: lp
      #     segment: minor
      #     previous: ${{ steps.get-latest-version.outputs.version }}
      #     description: 'minor test'

      # - id: patch
      #   uses: ./.github/actions/auto_versioning
      #   with:
      #     package: lp
      #     segment: patch
      #     previous: ${{ steps.get-latest-version.outputs.version }}
      #     description: 'patch test'

      # - id: dev
      #   uses: ./.github/actions/auto_versioning
      #   with:
      #     package: lp
      #     segment: dev
      #     previous: ${{ steps.get-latest-version.outputs.version }}
      #     description: 'dev test'
