name: versioning

on: push

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - id: ctx
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event }}
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0

      # - id: get-latest-version
      #   uses: ./.github/actions/get_latest_version
      #   with:
      #     package: lp

      # - id: minor
      #   uses: ./.github/actions/auto_versioning
      #   with:
      #     package: lp
      #     segment: minor
      #     previous: ${{ steps.get-latest-version.outputs.version }}
      #     description: 'minor test'

      # - id: patch
      #   uses: ./.github/actions/auto_versioning
      #   with:
      #     package: lp
      #     segment: patch
      #     previous: ${{ steps.get-latest-version.outputs.version }}
      #     description: 'patch test'

      # - id: dev
      #   uses: ./.github/actions/auto_versioning
      #   with:
      #     package: lp
      #     segment: dev
      #     previous: ${{ steps.get-latest-version.outputs.version }}
      #     description: 'dev test'
